// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPNslvBJliQjrZk-fH2jByl8xZf57hPL4',
    appId: '1:956206405942:web:89bbd2cf2189b46e017b97',
    messagingSenderId: '956206405942',
    projectId: 'dumy-5b659',
    authDomain: 'dumy-5b659.firebaseapp.com',
    storageBucket: 'dumy-5b659.appspot.com',
    measurementId: 'G-YD7SHFD9CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeX-xKzFSAIHH-0izWOJbVqDknlXcFeTw',
    appId: '1:956206405942:android:46246d323e36df6e017b97',
    messagingSenderId: '956206405942',
    projectId: 'dumy-5b659',
    storageBucket: 'dumy-5b659.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwpZsdtVhn-_VWGAfEZsYTHMtm_68sPO0',
    appId: '1:956206405942:ios:a0c5c1592aae374a017b97',
    messagingSenderId: '956206405942',
    projectId: 'dumy-5b659',
    storageBucket: 'dumy-5b659.appspot.com',
    iosBundleId: 'com.example.demoProject',
  );
}
